# 定义项目名称，方便在 Docker Desktop 中识别
name: web-project

services:
  # 定义一个名为 'db' 的服务
  db:
    # 使用 Bitnami 优化过的 PostgreSQL 最新版镜像
    image: bitnami/postgresql:latest
    # 给容器取一个好记的名字
    container_name: my_postgres_db
    # 端口映射: 将本机的 5432 端口映射到容器的 5432 端口
    # 这样我们的 FastAPI 应用就能通过 localhost:5432 连接到它
    ports:
      - "5432:5432"
    # 环境变量: 用于初始化数据库
    environment:
      - POSTGRES_USER=admin         # 设置用户名
      - POSTGRES_PASSWORD=123456    # 设置密码
      - POSTGRES_DB=app             # 设置要创建的数据库名
    # 数据卷: 将容器内的数据持久化到本地
    # 即使容器被删除，数据也不会丢失
    volumes:
      - postgres_data:/bitnami/postgresql
    # 重启策略: 除非手动停止，否则容器总会自动重启
    restart: unless-stopped

# 定义数据卷
volumes:
  postgres_data:
    driver: local